"""empty message

Revision ID: 2a761ef7b192
Revises: ed72b7b3c808
Create Date: 2024-05-30 10:27:43.041440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a761ef7b192'
down_revision: Union[str, None] = 'ed72b7b3c808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('current_sequence', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('sequence_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'sequence_number')
    op.drop_column('company', 'current_sequence')
    # ### end Alembic commands ###
