"""empty message

Revision ID: 3cf1454904f7
Revises: 2a761ef7b192
Create Date: 2024-06-18 19:05:58.768400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3cf1454904f7'
down_revision: Union[str, None] = '2a761ef7b192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
